# Generated by Django 5.2.9 on 2025-12-26 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('bio', models.TextField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('team_role', models.CharField(blank=True, max_length=50)),
                ('teams', models.ManyToManyField(blank=True, to='teams.team')),
            ],
        ),
    ]
